### ISSUE TITLE
Add sdk index for ufbt

### ISSUE THREAD

**Issue by jenrik** [Flipper-XFW/Xtreme-Website#2]
When using the `ufbt` tool for building and developing an app/plugin for the Flipper you need to configure it with a SDK corresponding to the firmware your Flipper is currently running. This can either be done by specifying a direct url to the packaged SDK zip, or more conveniently by pointing it to a JSON index of the latest release/build for all release channels (dev, release-candidate, release, ...). Consider adding a index to the website to help streamline compilation and development targeting Xtreme.

Index examples:

- [ofw](https://update.flipperzero.one/firmware/directory.json)
- [unleashed](https://up.unleashedflip.com/directory.json)

**Comment by ClaraCrazy** [comment]
We're already working on getting the SDK everywhere. I already got a nice idea on how that would look like as well. Shouldnt take too long

**Comment by ClaraCrazy** [comment]
After some discussion with the team, we concluded that the SDK shouldnt be on the flashing page, as to not confuse "normies". It will always be available on github, as it already is rn through actions, or in our discord server in the dev update channel.
